-- MySQL Script generated by MySQL Workbench
-- Wed Jul 21 12:37:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema esvidal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esvidal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esvidal` DEFAULT CHARACTER SET latin1 ;
USE `esvidal` ;

-- -----------------------------------------------------
-- Table `esvidal`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`admins` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'admin',
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT '1',
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admins_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`appointments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `date` DATE NOT NULL,
  `hour` TIME NOT NULL,
  `professional_id` INT UNSIGNED NOT NULL,
  `status` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'AVAILABLE',
  `booking_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5833
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`articles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `summary` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `featured_image_id` INT UNSIGNED NULL DEFAULT NULL,
  `slug_route_id` INT UNSIGNED NULL DEFAULT NULL,
  `category_id` INT UNSIGNED NULL DEFAULT NULL,
  `admin_id` INT UNSIGNED NULL DEFAULT NULL,
  `author_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`booking_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`booking_files` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_path` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `file_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `file_size` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `extension` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `owner` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'CLIENT',
  `booking_id` INT UNSIGNED NOT NULL,
  `professional_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `professional_email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `professional_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`booking_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`booking_notes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `note` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `booking_id` INT UNSIGNED NOT NULL,
  `professional_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `professional_email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `professional_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`bookings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `service` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `service_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `booking_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `client_id` INT UNSIGNED NULL DEFAULT NULL,
  `client_first_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `client_last_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `client_phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `client_email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `client_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `client_comment` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `professional_id` INT UNSIGNED NULL DEFAULT NULL,
  `professional_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `professional_email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `professional_comment` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `rescheduled` TINYINT(1) NULL DEFAULT '0',
  `rescheduled_date` DATETIME NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  `payment_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'CARD',
  `voucher_type` ENUM('BOLETA', 'FACTURA') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `voucher_document_number` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `voucher_business_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `accept_terms` TINYINT(1) NULL DEFAULT '1',
  `accept_privacy_politics` TINYINT(1) NULL DEFAULT '0',
  `booking_status` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'RESERVED',
  `payment_status` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'PENDING',
  `sub_total` DOUBLE(8,2) NULL DEFAULT '0.00',
  `total` DOUBLE(8,2) NULL DEFAULT '0.00',
  `payment_code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `payment_date` DATE NULL DEFAULT NULL,
  `culqi_token_id` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `culqi_charge_id` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `culqi_reference_code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `culqi_message` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `cip_code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `cip_code_exp_date` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `appointment_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `summary` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `featured_image_id` INT UNSIGNED NULL DEFAULT NULL,
  `slug_route_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`claims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`claims` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_adult` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `document_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `document_number` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `parent_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address_reference` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `department` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `province` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `district` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `detail` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `order` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `accept_data` TINYINT(1) NULL DEFAULT NULL,
  `claim_code` INT NULL DEFAULT NULL,
  `claim_code_text` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `product` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `service` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `claim_amount` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `claim_description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `claim` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `complaint` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `supplier_detail` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `file_path` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`clients` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `document_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `document_number` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `address` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `company_id` INT UNSIGNED NULL DEFAULT NULL,
  `type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'NATURAL',
  `ruc` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `business_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`companies` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `business_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `ruc` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `contact_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `expire_date` DATE NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`company_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`company_services` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `service_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `service_id` INT UNSIGNED NOT NULL,
  `price` DOUBLE(8,2) NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`contacts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `province` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `company_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `service_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `service_type_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `message` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `accept_information` TINYINT(1) NULL DEFAULT '0',
  `accept_terms` TINYINT(1) NULL DEFAULT '0',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`departments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`districts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1835
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `connection` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `queue` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `payload` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `exception` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`module_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`module_groups` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`modules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `icon` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `group_route` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '/',
  `module_group_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`module_menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`module_menus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `route` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `module_id` BIGINT UNSIGNED NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `module_menus_module_id_foreign` (`module_id` ASC) VISIBLE,
  CONSTRAINT `module_menus_module_id_foreign`
    FOREIGN KEY (`module_id`)
    REFERENCES `esvidal`.`modules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`multimedia_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`multimedia_resources` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_path` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `file_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `file_size` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `extension` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`pages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `position` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `slug_route_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT '1',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`professionals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`professionals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `linked_in_url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `facebook_url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `instagram_url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `summary` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `featured_image_id` INT UNSIGNED NULL DEFAULT NULL,
  `slug_route_id` INT UNSIGNED NULL DEFAULT NULL,
  `admin_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`provinces` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 196
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`role_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`role_admins` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT UNSIGNED NOT NULL,
  `admin_id` BIGINT UNSIGNED NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT '1',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`role_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`role_modules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT UNSIGNED NOT NULL,
  `module_id` BIGINT UNSIGNED NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_modules_role_id_foreign` (`role_id` ASC) VISIBLE,
  INDEX `role_modules_module_id_foreign` (`module_id` ASC) VISIBLE,
  CONSTRAINT `role_modules_module_id_foreign`
    FOREIGN KEY (`module_id`)
    REFERENCES `esvidal`.`modules` (`id`),
  CONSTRAINT `role_modules_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `esvidal`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`role_module_menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`role_module_menus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `module_menu_id` BIGINT UNSIGNED NOT NULL,
  `role_module_id` BIGINT UNSIGNED NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_module_menus_module_menu_id_foreign` (`module_menu_id` ASC) VISIBLE,
  INDEX `role_module_menus_role_module_id_foreign` (`role_module_id` ASC) VISIBLE,
  CONSTRAINT `role_module_menus_module_menu_id_foreign`
    FOREIGN KEY (`module_menu_id`)
    REFERENCES `esvidal`.`module_menus` (`id`),
  CONSTRAINT `role_module_menus_role_module_id_foreign`
    FOREIGN KEY (`role_module_id`)
    REFERENCES `esvidal`.`role_modules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`service_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`service_types` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `image_url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `service_id` INT UNSIGNED NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`services` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `summary` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `featured_image_id` INT UNSIGNED NULL DEFAULT NULL,
  `icon_image_id` INT UNSIGNED NULL DEFAULT NULL,
  `slug_route_id` INT UNSIGNED NULL DEFAULT NULL,
  `price` DOUBLE(8,2) NOT NULL,
  `discount_rate` DOUBLE(8,2) NULL DEFAULT '0.00',
  `offer_price` DOUBLE(8,2) NULL DEFAULT '0.00',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`settings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `param` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `value` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`slug_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`slug_routes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `model` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `model_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_routes_slug_unique` (`slug` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`testimonies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`testimonies` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `content` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `featured_image_id` INT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'CLIENTE',
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `esvidal`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`USUARIOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`PERSONA` (
  `personaID` INT NOT NULL AUTO_INCREMENT,
  `aNombre01` VARCHAR(45) NOT NULL,
  `aNombre02` VARCHAR(45) NOT NULL,
  `aNombre03` VARCHAR(45) NOT NULL,
  `aApellido01` VARCHAR(45) NOT NULL,
  `aApellido02` VARCHAR(45) NOT NULL,
  `aEmail` VARCHAR(45) NOT NULL,
  `eTipo` VARCHAR(45) NOT NULL,
  `eEstado` VARCHAR(45) NOT NULL,
  `aCelular` VARCHAR(45) NOT NULL,
  `aFechaNacimiento` VARCHAR(45) NOT NULL,
  `aLugarNacimiento` VARCHAR(45) NOT NULL,
  `bHijos` TINYINT NOT NULL,
  `aFax` VARCHAR(45) NULL,
  PRIMARY KEY (`personaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`CLIENTE` (
  `clienteID` INT NOT NULL AUTO_INCREMENT,
  `personaID` INT NOT NULL,
  `aTipoDocumento` VARCHAR(45) NOT NULL,
  `aNrDocumento` VARCHAR(45) NOT NULL,
  `aRazonSocial` VARCHAR(45) NULL,
  `aRUC` VARCHAR(45) NULL,
  `aWeb` VARCHAR(45) NULL,
  `eTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`clienteID`),
  INDEX `fk_CLIENTE_PERSONA1_idx` (`personaID` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_PERSONA1`
    FOREIGN KEY (`personaID`)
    REFERENCES `esvidal`.`PERSONA` (`personaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`CARGO` (
  `cargoID` INT NOT NULL AUTO_INCREMENT,
  `aNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cargoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`PROFESIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`PROFESIONAL` (
  `profesionalID` INT NOT NULL AUTO_INCREMENT,
  `personaID` INT NOT NULL,
  `cargoID` INT NOT NULL,
  `icoImagen` VARCHAR(45) NOT NULL,
  `aUrlLinkedin` VARCHAR(45) NOT NULL,
  `aUrlFacebook` VARCHAR(45) NULL,
  `aUrlInstagram` VARCHAR(45) NULL,
  PRIMARY KEY (`profesionalID`),
  INDEX `fk_PROFESIONAL_PERSONA1_idx` (`personaID` ASC) VISIBLE,
  INDEX `fk_PROFESIONAL_CARGO1_idx` (`cargoID` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESIONAL_PERSONA1`
    FOREIGN KEY (`personaID`)
    REFERENCES `esvidal`.`PERSONA` (`personaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESIONAL_CARGO1`
    FOREIGN KEY (`cargoID`)
    REFERENCES `esvidal`.`CARGO` (`cargoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`SERVICIO` (
  `servicioID` INT NOT NULL AUTO_INCREMENT,
  `aNombre` VARCHAR(45) NOT NULL,
  `icoImagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`servicioID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`TIPO_SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`TIPO_SERVICIO` (
  `tipoServicioID` INT NOT NULL AUTO_INCREMENT,
  `servicioID` INT NOT NULL,
  `aNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipoServicioID`),
  INDEX `fk_TIPO_SERVICIO_SERVICIO1_idx` (`servicioID` ASC) VISIBLE,
  CONSTRAINT `fk_TIPO_SERVICIO_SERVICIO1`
    FOREIGN KEY (`servicioID`)
    REFERENCES `esvidal`.`SERVICIO` (`servicioID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`PROFESIONAL_SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`PROFESIONAL_SERVICIO` (
  `profesionalServicioID` INT NOT NULL AUTO_INCREMENT,
  `servicioID` INT NOT NULL,
  `profesionalID` INT NOT NULL,
  INDEX `fk_SERVICIO_has_PROFESIONAL_PROFESIONAL1_idx` (`profesionalID` ASC) VISIBLE,
  INDEX `fk_SERVICIO_has_PROFESIONAL_SERVICIO1_idx` (`servicioID` ASC) VISIBLE,
  PRIMARY KEY (`profesionalServicioID`),
  CONSTRAINT `fk_SERVICIO_has_PROFESIONAL_SERVICIO1`
    FOREIGN KEY (`servicioID`)
    REFERENCES `esvidal`.`SERVICIO` (`servicioID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICIO_has_PROFESIONAL_PROFESIONAL1`
    FOREIGN KEY (`profesionalID`)
    REFERENCES `esvidal`.`PROFESIONAL` (`profesionalID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`CONTRASENIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`CONTRASENIA` (
  `contraseniaID` INT NOT NULL AUTO_INCREMENT,
  `aContrasenia` VARCHAR(45) NOT NULL,
  `personaID` INT NOT NULL,
  `eTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`contraseniaID`),
  INDEX `fk_CONTRASENIA_PERSONA1_idx` (`personaID` ASC) VISIBLE,
  CONSTRAINT `fk_CONTRASENIA_PERSONA1`
    FOREIGN KEY (`personaID`)
    REFERENCES `esvidal`.`PERSONA` (`personaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`USER` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `CONTRASENIA_contraseniaID` INT NOT NULL,
  `login` INT NOT NULL,
  `dateLogin` DATETIME NULL,
  `dateUnlogin` DATETIME NULL,
  `dateUltimaConexion` DATETIME NULL,
  `bConectado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_USER_CONTRASENIA1_idx` (`CONTRASENIA_contraseniaID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_CONTRASENIA1`
    FOREIGN KEY (`CONTRASENIA_contraseniaID`)
    REFERENCES `esvidal`.`CONTRASENIA` (`contraseniaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`IDIOMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`IDIOMA` (
  `idiomaID` INT NOT NULL AUTO_INCREMENT,
  `aNombre` VARCHAR(45) NOT NULL,
  `aISO639_2B` VARCHAR(3) NOT NULL,
  `bDefault` TINYINT NOT NULL,
  PRIMARY KEY (`idiomaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`PAIS` (
  `paisID` INT NOT NULL AUTO_INCREMENT,
  `aNombre` VARCHAR(45) NOT NULL,
  `aNombreING` VARCHAR(45) NOT NULL,
  `aPrefTelefonico` VARCHAR(45) NOT NULL,
  `aISO3166` VARCHAR(45) NOT NULL,
  `idiomaID` INT NOT NULL,
  PRIMARY KEY (`paisID`),
  INDEX `fk_PAIS_IDIOMA1_idx` (`idiomaID` ASC) VISIBLE,
  CONSTRAINT `fk_PAIS_IDIOMA1`
    FOREIGN KEY (`idiomaID`)
    REFERENCES `esvidal`.`IDIOMA` (`idiomaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`DIRECCION` (
  `direccionID` INT NOT NULL AUTO_INCREMENT,
  `aCalle` VARCHAR(45) NOT NULL,
  `aCodigoPostal` VARCHAR(45) NOT NULL,
  `aCiudad` VARCHAR(45) NOT NULL,
  `aPais` VARCHAR(45) NOT NULL,
  `personaID` INT NOT NULL,
  `paisID` INT NOT NULL,
  PRIMARY KEY (`direccionID`),
  INDEX `fk_DIRECCION_PERSONA1_idx` (`personaID` ASC) VISIBLE,
  INDEX `fk_DIRECCION_PAIS1_idx` (`paisID` ASC) VISIBLE,
  CONSTRAINT `fk_DIRECCION_PERSONA1`
    FOREIGN KEY (`personaID`)
    REFERENCES `esvidal`.`PERSONA` (`personaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIRECCION_PAIS1`
    FOREIGN KEY (`paisID`)
    REFERENCES `esvidal`.`PAIS` (`paisID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`CONEXION_BANCARIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`CONEXION_BANCARIA` (
  `conexionBancariaID` INT NULL AUTO_INCREMENT,
  `aNumeroCuenta` VARCHAR(45) NOT NULL,
  `aIBAN` VARCHAR(45) NOT NULL,
  `aSWIFT` VARCHAR(45) NULL,
  `aComentario` VARCHAR(45) NULL,
  `personaID` INT NOT NULL,
  PRIMARY KEY (`conexionBancariaID`),
  INDEX `fk_CONEXION_BANCARIA_PERSONA1_idx` (`personaID` ASC) VISIBLE,
  CONSTRAINT `fk_CONEXION_BANCARIA_PERSONA1`
    FOREIGN KEY (`personaID`)
    REFERENCES `esvidal`.`PERSONA` (`personaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`TITULO_ABREVIADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`TITULO_ABREVIADO` (
  `tituloAbreviadoID` INT NOT NULL AUTO_INCREMENT,
  `aTitulo` VARCHAR(45) NOT NULL,
  `bMostrar` VARCHAR(45) NOT NULL,
  `personaID` INT NOT NULL,
  PRIMARY KEY (`tituloAbreviadoID`),
  INDEX `fk_TITULO_ABREVIADO_PERSONA1_idx` (`personaID` ASC) VISIBLE,
  CONSTRAINT `fk_TITULO_ABREVIADO_PERSONA1`
    FOREIGN KEY (`personaID`)
    REFERENCES `esvidal`.`PERSONA` (`personaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`BANCOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`BANCOS` (
  `bancosID` INT NOT NULL AUTO_INCREMENT,
  `DIRECCION_direccionID` INT NOT NULL,
  `aBanco` VARCHAR(45) NOT NULL,
  `aTelefono` VARCHAR(45) NOT NULL,
  `aFax` VARCHAR(45) NOT NULL,
  `aEmail` VARCHAR(45) NOT NULL,
  `aWeb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bancosID`),
  INDEX `fk_BANCOS_DIRECCION1_idx` (`DIRECCION_direccionID` ASC) VISIBLE,
  CONSTRAINT `fk_BANCOS_DIRECCION1`
    FOREIGN KEY (`DIRECCION_direccionID`)
    REFERENCES `esvidal`.`DIRECCION` (`direccionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`TARJETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`TARJETA` (
  `tarjetaID` INT NOT NULL AUTO_INCREMENT,
  `aNumero` VARCHAR(45) NOT NULL,
  `aCVV` VARCHAR(45) NOT NULL,
  `dateMesExpiracion` VARCHAR(45) NOT NULL,
  `dateAnioExpiracion` VARCHAR(45) NOT NULL,
  `aNombreTitular` VARCHAR(45) NOT NULL,
  `aApellidoTitular` VARCHAR(45) NOT NULL,
  `clienteID` INT NOT NULL,
  PRIMARY KEY (`tarjetaID`),
  INDEX `fk_TARJETA_CLIENTE1_idx` (`clienteID` ASC) VISIBLE,
  CONSTRAINT `fk_TARJETA_CLIENTE1`
    FOREIGN KEY (`clienteID`)
    REFERENCES `esvidal`.`CLIENTE` (`clienteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`RESERVA` (
  `reservaID` INT NOT NULL AUTO_INCREMENT,
  `dateCreacion` DATETIME NOT NULL,
  `eTipoAsesoria` VARCHAR(45) NOT NULL,
  `dateCita` DATE NOT NULL,
  `timeCita` TIME NOT NULL,
  `eTipoComprobante` VARCHAR(45) NOT NULL,
  `aRazonSocial` VARCHAR(45) NOT NULL,
  `eEstado` VARCHAR(45) NOT NULL,
  `tipoServicioID` INT NOT NULL,
  `clienteID` INT NOT NULL,
  `profesionalID` INT NULL,
  `tarjetaID` INT NULL,
  PRIMARY KEY (`reservaID`),
  INDEX `fk_RESERVA_TIPO_SERVICIO1_idx` (`tipoServicioID` ASC) VISIBLE,
  INDEX `fk_RESERVA_CLIENTE1_idx` (`clienteID` ASC) VISIBLE,
  INDEX `fk_RESERVA_PROFESIONAL1_idx` (`profesionalID` ASC) VISIBLE,
  INDEX `fk_RESERVA_TARJETA1_idx` (`tarjetaID` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVA_TIPO_SERVICIO1`
    FOREIGN KEY (`tipoServicioID`)
    REFERENCES `esvidal`.`TIPO_SERVICIO` (`tipoServicioID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_CLIENTE1`
    FOREIGN KEY (`clienteID`)
    REFERENCES `esvidal`.`CLIENTE` (`clienteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_PROFESIONAL1`
    FOREIGN KEY (`profesionalID`)
    REFERENCES `esvidal`.`PROFESIONAL` (`profesionalID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_TARJETA1`
    FOREIGN KEY (`tarjetaID`)
    REFERENCES `esvidal`.`TARJETA` (`tarjetaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esvidal`.`ARCHIVO_RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esvidal`.`ARCHIVO_RESERVA` (
  `archivoReservaID` INT NOT NULL AUTO_INCREMENT,
  `reservaID` INT NOT NULL,
  `personaID` INT NOT NULL,
  `aNombreDocumento` VARCHAR(45) NOT NULL,
  `aUrlDocumento` VARCHAR(45) NOT NULL,
  `eTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`archivoReservaID`),
  INDEX `fk_ARCHIVO_RESERVA1_idx` (`reservaID` ASC) VISIBLE,
  INDEX `fk_ARCHIVO_RESERVA_PERSONA1_idx` (`personaID` ASC) VISIBLE,
  CONSTRAINT `fk_ARCHIVO_RESERVA1`
    FOREIGN KEY (`reservaID`)
    REFERENCES `esvidal`.`RESERVA` (`reservaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARCHIVO_RESERVA_PERSONA1`
    FOREIGN KEY (`personaID`)
    REFERENCES `esvidal`.`PERSONA` (`personaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
